# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


import time
from PyQt6.QtCore import QTimer, Qt
from PyQt6 import QtCore, QtGui, QtWidgets
from UI_Page_6 import Ui_MainWindow_Page_6
from Out_file_images import qt_resource_data

from PyQt6 import QtCore, QtWidgets
import sys
from PyQt6 import QtCore, QtWidgets
import sys
from UI_Page_2 import Ui_MainWindow_Page_2
from UI_Page_3 import Ui_MainWindow_Page_3
from chart_window import (
    WindowAgeEfficacy,
    WindowEfficacyDayInWeek,
    WindowSexEfficacy,
)  # Import the chart window class


class ChartEfficacyDayInWeek(WindowEfficacyDayInWeek):
    print("ChartAgeEfficacy(WindowAgeEfficacy)")

    def __init__(self):
        super().__init__()


class ChartAgeEfficacy(WindowAgeEfficacy):
    def __init__(self):
        super().__init__()


class ChartSexEfficacy(WindowSexEfficacy):
    def __init__(self):
        super().__init__()


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1463, 1133)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet(
            "background-color: rgb(154, 148, 148);\n"
            "background-color: rgb(255, 202, 189);\n"
            "background-color: rgb(227, 224, 246);"
        )
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_4 = QtWidgets.QFrame(parent=self.frame)
        self.frame_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_13 = QtWidgets.QFrame(parent=self.frame_4)
        self.frame_13.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_13.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_13.setStyleSheet(
            "background-color: rgb(255, 216, 228);\n"
            "border-style: solid;\n"
            "border-color: black;\n"
            "border-radius: 30px;\n"
            "border-style: solid;"
        )
        self.frame_13.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_9 = QtWidgets.QLabel(parent=self.frame_13)
        self.label_9.setStyleSheet('font: 18pt "Papyrus";\n' "color: rgb(252, 1, 7);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.frame_13)
        self.pushButton_5.setStyleSheet("color: rgb(0, 0, 0);")
        self.pushButton_5.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(":/newPrefix/srearch.png"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.pushButton_5.setIcon(icon)
        self.pushButton_5.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_6.addWidget(self.pushButton_5)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.frame_13)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("color: rgb(0, 0, 0);")
        self.lineEdit.setPlaceholderText("Tìm kiếm nhanh ...")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_6.addWidget(self.lineEdit)
        self.verticalLayout_9.addWidget(self.frame_13)
        self.frame_12 = QtWidgets.QFrame(parent=self.frame_4)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.frame_12.setFont(font)
        self.frame_12.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.frame_12.setMouseTracking(True)
        self.frame_12.setTabletTracking(False)
        self.frame_12.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.frame_12.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.frame_12.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n"
            "border-style: solid;\n"
            "border-color: rgb(255, 255, 255);\n"
            "border-radius: 10px;"
        )
        self.frame_12.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.frame_12)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_3.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet(
            "background-color: rgb(49, 17, 29);\n"
            "border-style: solid;\n"
            "border-radius: 20px;\n"
            "color: rgb(255, 255, 255);\n"
            "checked { background-color: rgb(125, 82, 96) ;}"
        )
        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap(":/newPrefix/profile2-removebg-preview.png"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_5.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame_12)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButton_2.setStyleSheet(
            "background-color: rgb(49, 17, 29);\n"
            "border-style: solid;\n"
            "border-radius: 20px;\n"
            "color: rgb(255, 255, 255);"
        )
        icon2 = QtGui.QIcon()
        icon2.addPixmap(
            QtGui.QPixmap(":/newPrefix/Recruitment-removebg-preview.png"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_5.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(parent=self.frame_12)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButton.setStyleSheet(
            "background-color: rgb(49, 17, 29);\n"
            "border-style: solid;\n"
            "border-radius: 20px;\n"
            "color: rgb(255, 255, 255);"
        )
        icon3 = QtGui.QIcon()
        icon3.addPixmap(
            QtGui.QPixmap(":/newPrefix/danhGia.png"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.pushButton.setIcon(icon3)
        self.pushButton.setIconSize(QtCore.QSize(24, 24))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_5.addWidget(self.pushButton)
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.frame_12)
        self.pushButton_10.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_10.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButton_10.setStyleSheet(
            "background-color: rgb(49, 17, 29);\n"
            "border-style: solid;\n"
            "border-radius: 20px;\n"
            "color: rgb(255, 255, 255);"
        )
        icon4 = QtGui.QIcon()
        icon4.addPixmap(
            QtGui.QPixmap(":/newPrefix/KhenThuong.png"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.pushButton_10.setIcon(icon4)
        self.pushButton_10.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_5.addWidget(self.pushButton_10)
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.frame_12)
        self.pushButton_9.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_9.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButton_9.setStyleSheet(
            "background-color: rgb(49, 17, 29);\n"
            "border-style: solid;\n"
            "border-radius: 20px;\n"
            "color: rgb(255, 255, 255);"
        )
        icon5 = QtGui.QIcon()
        icon5.addPixmap(
            QtGui.QPixmap(":/newPrefix/Thutuc.png"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.pushButton_9.setIcon(icon5)
        self.pushButton_9.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_5.addWidget(self.pushButton_9)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.frame_12)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_4.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButton_4.setStyleSheet(
            "background-color: rgb(49, 17, 29);\n"
            "border-style: solid;\n"
            "border-radius: 20px;\n"
            "color: rgb(255, 255, 255);"
        )
        icon6 = QtGui.QIcon()
        icon6.addPixmap(
            QtGui.QPixmap(":/newPrefix/squares-clipartA-removebg-preview.png"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.pushButton_4.setIcon(icon6)
        self.pushButton_4.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_5.addWidget(self.pushButton_4)
        self.verticalLayout_9.addWidget(self.frame_12)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(parent=self.frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.frame_5)
        font = QtGui.QFont()
        font.setFamily("American Typewriter")
        font.setPointSize(48)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet(
            'font: 48pt "American Typewriter";\n'
            "color: rgb(49, 17, 29);\n"
            "background-color: rgb(255, 216, 228);\n"
            "font-weight:bold;"
        )
        self.label.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setStyleSheet(
            "spacing: 20px;\n"
            "border-color: rgb(255, 255, 255);\n"
            "border-width : 0px;"
        )
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(40)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_6 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_6.setStyleSheet(
            "border-radius: 30px;\n"
            "border-style: solid;\n"
            "background-color: rgb(255, 216, 228);\n"
            "margin"
        )
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_2.setEnabled(True)
        self.label_2.setMinimumSize(QtCore.QSize(0, 250))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 250))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setAccessibleDescription("")
        self.label_2.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet(
            "background-image: url(:/newPrefix/IELTS-Eligibility-1.png);\n"
            "color: rgb(255, 216, 228);\n"
            "border-radius: 30px;"
        )
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(
            self.label_2, 0, QtCore.Qt.AlignmentFlag.AlignTop
        )
        self.pushButton_search = QtWidgets.QPushButton(parent=self.frame_6)
        self.pushButton_search.setMinimumSize(QtCore.QSize(0, 80))
        self.pushButton_search.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_search.setFont(font)
        self.pushButton_search.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButton_search.setStyleSheet(
            'font: 75 30pt "Arial";\n'
            "border-color: rgb(255, 216, 228);\n"
            "color: rgb(49, 17, 29);\n"
            "background-color: rgb(255, 216, 228);\n"
            "border-radius: 30px;\n"
            "\n"
            "pressed { background-color: red }"
        )
        self.pushButton_search.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_search.setObjectName("pushButton_search")
        self.verticalLayout_3.addWidget(
            self.pushButton_search, 0, QtCore.Qt.AlignmentFlag.AlignLeft
        )
        self.horizontalLayout_2.addWidget(
            self.frame_6, 0, QtCore.Qt.AlignmentFlag.AlignTop
        )
        self.frame_7 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_7.setStyleSheet(
            "border-radius: 30px;\n"
            "border-style: solid;\n"
            "background-color: rgb(255, 216, 228);"
        )
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_3.setMinimumSize(QtCore.QSize(0, 250))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 250))
        self.label_3.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet("background-image: url(:/newPrefix/time2.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.pushButton_ChamCong = QtWidgets.QPushButton(parent=self.frame_7)
        self.pushButton_ChamCong.setMinimumSize(QtCore.QSize(0, 80))
        self.pushButton_ChamCong.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_ChamCong.setFont(font)
        self.pushButton_ChamCong.setStyleSheet(
            'font: 75 30pt "Arial";\n'
            "border-color: rgb(255, 216, 228);\n"
            "color: rgb(49, 17, 29);\n"
            "background-color: rgb(255, 216, 228);\n"
            "border-radius: 30px;\n"
            ""
        )
        self.pushButton_ChamCong.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_ChamCong.setObjectName("pushButton_ChamCong")
        self.verticalLayout_4.addWidget(
            self.pushButton_ChamCong, 0, QtCore.Qt.AlignmentFlag.AlignLeft
        )
        self.horizontalLayout_2.addWidget(
            self.frame_7, 0, QtCore.Qt.AlignmentFlag.AlignTop
        )
        self.frame_8 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_8.setStyleSheet(
            "border-radius: 30px;\n"
            "border-style: solid;\n"
            "background-color: rgb(255, 216, 228);"
        )
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_4.setMinimumSize(QtCore.QSize(0, 250))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 250))
        self.label_4.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_4.setAutoFillBackground(False)
        self.label_4.setStyleSheet(
            "background-image: url(:/newPrefix/dayaweek.png);\n" ""
        )
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.pushButton_EfficacyDayInWeek = QtWidgets.QPushButton(parent=self.frame_8)
        self.pushButton_EfficacyDayInWeek.setMinimumSize(QtCore.QSize(0, 80))
        self.pushButton_EfficacyDayInWeek.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_EfficacyDayInWeek.setFont(font)
        self.pushButton_EfficacyDayInWeek.setStyleSheet(
            'font: 75 30pt "Arial";\n'
            "border-color: rgb(255, 216, 228);\n"
            "color: rgb(49, 17, 29);\n"
            "background-color: rgb(255, 216, 228);\n"
            "border-radius: 30px;\n"
            ""
        )
        self.pushButton_EfficacyDayInWeek.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_EfficacyDayInWeek.setObjectName("pushButton_EfficacyDayInWeek")
        self.verticalLayout_5.addWidget(
            self.pushButton_EfficacyDayInWeek, 0, QtCore.Qt.AlignmentFlag.AlignLeft
        )
        self.horizontalLayout_2.addWidget(
            self.frame_8, 0, QtCore.Qt.AlignmentFlag.AlignTop
        )
        self.gridLayout.addWidget(self.frame_2, 1, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(40)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_9 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_9.setStyleSheet(
            "border-radius: 30px;\n"
            "border-style: solid;\n"
            "background-color: rgb(255, 216, 228);"
        )
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(parent=self.frame_9)
        self.label_5.setMinimumSize(QtCore.QSize(0, 250))
        self.label_5.setMaximumSize(QtCore.QSize(700, 250))
        self.label_5.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.label_5.setAutoFillBackground(False)
        self.label_5.setStyleSheet("background-image: url(:/newPrefix/aaaaa.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.pushButton_AgeEfficacy = QtWidgets.QPushButton(parent=self.frame_9)
        self.pushButton_AgeEfficacy.setMinimumSize(QtCore.QSize(0, 80))
        self.pushButton_AgeEfficacy.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_AgeEfficacy.setFont(font)
        self.pushButton_AgeEfficacy.setStyleSheet(
            'font: 75 30pt "Arial";\n'
            "border-color: rgb(255, 216, 228);\n"
            "color: rgb(49, 17, 29);\n"
            "background-color: rgb(255, 216, 228);\n"
            "border-radius: 30px;\n"
            ""
        )
        self.pushButton_AgeEfficacy.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_AgeEfficacy.setObjectName("pushButton_AgeEfficacy")
        self.verticalLayout_6.addWidget(
            self.pushButton_AgeEfficacy, 0, QtCore.Qt.AlignmentFlag.AlignLeft
        )
        self.horizontalLayout_3.addWidget(
            self.frame_9, 0, QtCore.Qt.AlignmentFlag.AlignTop
        )
        self.frame_10 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_10.setStyleSheet(
            "border-radius: 30px;\n"
            "border-style: solid;\n"
            "background-color: rgb(255, 216, 228);"
        )
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_6 = QtWidgets.QLabel(parent=self.frame_10)
        self.label_6.setMinimumSize(QtCore.QSize(0, 250))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 250))
        self.label_6.setStyleSheet(
            "background-image: url(:/newPrefix/menandwomen.png);"
        )
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6)
        self.pushButton_SexEfficacy = QtWidgets.QPushButton(parent=self.frame_10)
        self.pushButton_SexEfficacy.setMinimumSize(QtCore.QSize(0, 80))
        self.pushButton_SexEfficacy.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_SexEfficacy.setFont(font)
        self.pushButton_SexEfficacy.setStyleSheet(
            'font: 75 30pt "Arial";\n'
            "border-color: rgb(255, 216, 228);\n"
            "color: rgb(49, 17, 29);\n"
            "background-color: rgb(255, 216, 228);\n"
            "border-radius: 30px;\n"
            ""
        )
        self.pushButton_SexEfficacy.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_SexEfficacy.setObjectName("pushButton_SexEfficacy")
        self.verticalLayout_7.addWidget(
            self.pushButton_SexEfficacy, 0, QtCore.Qt.AlignmentFlag.AlignLeft
        )
        self.horizontalLayout_3.addWidget(
            self.frame_10, 0, QtCore.Qt.AlignmentFlag.AlignTop
        )
        self.frame_11 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_11.setStyleSheet(
            "border-radius: 30px;\n"
            "border-style: solid;\n"
            "background-color: rgb(255, 216, 228);"
        )
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_7 = QtWidgets.QLabel(parent=self.frame_11)
        self.label_7.setMinimumSize(QtCore.QSize(0, 250))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 250))
        self.label_7.setStyleSheet(
            "background-image: url(:/newPrefix/11111.png);\n"
            "background-image: url(:/newPrefix/demand-forecasting-feature-image.png);"
        )
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_8.addWidget(self.label_7)
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.frame_11)
        self.pushButton_6.setMinimumSize(QtCore.QSize(0, 80))
        self.pushButton_6.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet(
            'font: 75 30pt "Arial";\n'
            "border-color: rgb(255, 216, 228);\n"
            "color: rgb(49, 17, 29);\n"
            "background-color: rgb(255, 216, 228);\n"
            "border-radius: 30px;\n"
            ""
        )
        self.pushButton_6.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_8.addWidget(
            self.pushButton_6, 0, QtCore.Qt.AlignmentFlag.AlignLeft
        )
        self.horizontalLayout_3.addWidget(
            self.frame_11, 0, QtCore.Qt.AlignmentFlag.AlignTop
        )
        self.gridLayout.addWidget(self.frame_3, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        # Trang hiện tại là trang đầu tiên
        self.trang_hien_tai = 1

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(
            _translate("MainWindow", "ASIM Viet Nam - Phòng Tài Chính - Nhân Sự")
        )
        self.pushButton_3.setText(_translate("MainWindow", "Hồ sơ nhân viên"))
        self.pushButton_2.setText(_translate("MainWindow", "Tuyển dụng - Tiếp nhận"))
        self.pushButton.setText(_translate("MainWindow", "Đánh giá - Đào tạo"))
        self.pushButton_10.setText(_translate("MainWindow", "Khen thưởng"))
        self.pushButton_9.setText(_translate("MainWindow", "Thủ tục"))
        self.pushButton_4.setText(_translate("MainWindow", "Danh mục"))
        self.label.setText(
            _translate("MainWindow", "ASIM VIET NAM - PHÒNG TÀI CHÍNH - NHÂN SỰ ")
        )
        self.pushButton_search.setText(_translate("MainWindow", "   Tra cứu thông tin"))
        self.pushButton_ChamCong.setText(_translate("MainWindow", "   Bảng chấm công "))
        self.pushButton_EfficacyDayInWeek.setText(
            _translate("MainWindow", "   Hiệu quả làm việc trong tuần")
        )
        self.pushButton_AgeEfficacy.setText(
            _translate("MainWindow", "   Ảnh hưởng tuổi đến năng suất")
        )
        self.pushButton_SexEfficacy.setText(
            _translate("MainWindow", "   Giới tính - Hiệu quả làm việc")
        )
        self.pushButton_6.setText(
            _translate("MainWindow", "   Dự đoán hiệu suất làm việc ")
        )

    def next_page_2(self):
        self.pushButton_search.setStyleSheet(
            'font: 75 30pt "Arial";\n'
            "border-color: rgb(255, 216, 228);\n"
            "color: rgb(239, 184, 200);\n"
            "border-radius: 30px;"
        )
        self.frame_6.setStyleSheet(
            "border-radius: 30px;\n"
            "border-style: solid;\n"
            "background-color: rgb(99, 59, 72);\n"
            "margin"
        )
        if self.trang_hien_tai == 1:
            self.trang_hien_tai = 2
            self.trang_moi = QtWidgets.QMainWindow()  # Create a new QMainWindow
            self.ui_page_2 = Ui_MainWindow_Page_2()
            self.ui_page_2.setupUi(
                self.trang_moi
            )  # Set up Ui_MainWindow_Page_2 on the new QMainWindow
            self.trang_moi.show()  # Show the new page
            self.pushButton_search.setStyleSheet(
                'font: 75 30pt "Arial";\n'
                "border-color: rgb(255, 216, 228);\n"
                "color: rgb(49, 17, 29);\n"
                "background-color: rgb(255, 216, 228);\n"
                "border-radius: 30px;\n"
                "\n"
                "pressed { background-color: red }"
            )
            self.frame_6.setStyleSheet(
                "border-radius: 30px;\n"
                "border-style: solid;\n"
                "background-color: rgb(255, 216, 228);\n"
                "margin"
            )
        else:
            self.trang_hien_tai = 1
            # Return to the main page
            self.trang_moi.close()  # Close the current page

    def next_page_3(self):
        self.pushButton_ChamCong.setStyleSheet(
            'font: 75 30pt "Arial";\n'
            "border-color: rgb(255, 216, 228);\n"
            "color: rgb(239, 184, 200);\n"
            "border-radius: 30px;"
        )
        self.frame_7.setStyleSheet(
            "border-radius: 30px;\n"
            "border-style: solid;\n"
            "background-color: rgb(99, 59, 72);\n"
            "margin"
        )
        if self.trang_hien_tai == 1:
            self.trang_hien_tai = 2
            self.trang_moi = QtWidgets.QMainWindow()  # Create a new QMainWindow
            self.ui_page_3 = Ui_MainWindow_Page_3()
            self.ui_page_3.setupUi(
                self.trang_moi
            )  # Set up Ui_MainWindow_Page_2 on the new QMainWindow
            self.trang_moi.show()  # Show the new page
            self.pushButton_ChamCong.setStyleSheet(
                'font: 75 30pt "Arial";\n'
                "border-color: rgb(255, 216, 228);\n"
                "color: rgb(49, 17, 29);\n"
                "background-color: rgb(255, 216, 228);\n"
                "border-radius: 30px;\n"
                "\n"
                "pressed { background-color: red }"
            )
            self.frame_7.setStyleSheet(
                "border-radius: 30px;\n"
                "border-style: solid;\n"
                "background-color: rgb(255, 216, 228);\n"
                "margin"
            )
        else:
            self.trang_hien_tai = 1
            # Return to the main page
            self.trang_moi.close()  # Close the current page

    def show_chart_window_efficacy_day_in_week(self):
        self.pushButton_EfficacyDayInWeek.setStyleSheet(
            'font: 75 30pt "Arial";\n'
            "border-color: rgb(255, 216, 228);\n"
            "color: rgb(239, 184, 200);\n"
            "border-radius: 30px;"
        )
        self.frame_8.setStyleSheet(
            "border-radius: 30px;\n"
            "border-style: solid;\n"
            "background-color: rgb(99, 59, 72);\n"
            "margin"
        )
        print("self.frame_8.setStyleSheet")

        self.chart_window = ChartEfficacyDayInWeek()

        self.pushButton_EfficacyDayInWeek.setStyleSheet(
            'font: 75 30pt "Arial";\n'
            "border-color: rgb(255, 216, 228);\n"
            "color: rgb(49, 17, 29);\n"
            "background-color: rgb(255, 216, 228);\n"
            "border-radius: 30px;\n"
            "\n"
            "pressed { background-color: red }"
        )
        self.frame_8.setStyleSheet(
            "border-radius: 30px;\n"
            "border-style: solid;\n"
            "background-color: rgb(255, 216, 228);\n"
            "margin"
        )

    def show_chart_window_age_efficacy(self):
        self.pushButton_AgeEfficacy.setStyleSheet(
            'font: 75 30pt "Arial";\n'
            "border-color: rgb(255, 216, 228);\n"
            "color: rgb(239, 184, 200);\n"
            "border-radius: 30px;"
        )
        self.frame_9.setStyleSheet(
            "border-radius: 30px;\n"
            "border-style: solid;\n"
            "background-color: rgb(99, 59, 72);\n"
            "margin"
        )
        self.chart_window = ChartAgeEfficacy()
        self.pushButton_AgeEfficacy.setStyleSheet(
            'font: 75 30pt "Arial";\n'
            "border-color: rgb(255, 216, 228);\n"
            "color: rgb(49, 17, 29);\n"
            "background-color: rgb(255, 216, 228);\n"
            "border-radius: 30px;\n"
            "\n"
            "pressed { background-color: red }"
        )
        self.frame_9.setStyleSheet(
            "border-radius: 30px;\n"
            "border-style: solid;\n"
            "background-color: rgb(255, 216, 228);\n"
            "margin"
        )

    def show_chart_window_sex_efficacy(self):
        self.pushButton_SexEfficacy.setStyleSheet(
            'font: 75 30pt "Arial";\n'
            "border-color: rgb(255, 216, 228);\n"
            "color: rgb(239, 184, 200);\n"
            "border-radius: 30px;"
        )
        self.frame_10.setStyleSheet(
            "border-radius: 30px;\n"
            "border-style: solid;\n"
            "background-color: rgb(99, 59, 72);\n"
            "margin"
        )
        self.chart_window = ChartSexEfficacy()
        # self.chart_window.show()
        self.pushButton_SexEfficacy.setStyleSheet(
            'font: 75 30pt "Arial";\n'
            "border-color: rgb(255, 216, 228);\n"
            "color: rgb(49, 17, 29);\n"
            "background-color: rgb(255, 216, 228);\n"
            "border-radius: 30px;\n"
            "\n"
            "pressed { background-color: red }"
        )
        self.frame_10.setStyleSheet(
            "border-radius: 30px;\n"
            "border-style: solid;\n"
            "background-color: rgb(255, 216, 228);\n"
            "margin"
        )

    def next_page_6(self):
        self.pushButton_6.setStyleSheet(
            'font: 75 30pt "Arial";\n'
            "border-color: rgb(255, 216, 228);\n"
            "color: rgb(239, 184, 200);\n"
            "border-radius: 30px;"
        )
        self.frame_11.setStyleSheet(
            "border-radius: 30px;\n"
            "border-style: solid;\n"
            "background-color: rgb(99, 59, 72);\n"
            "margin"
        )
        if self.trang_hien_tai == 1:
            self.trang_hien_tai = 2
            self.trang_moi = QtWidgets.QMainWindow()  # Create a new QMainWindow
            self.ui_page_3 = Ui_MainWindow_Page_6()
            self.ui_page_3.setupUi(
                self.trang_moi
            )  # Set up Ui_MainWindow_Page_2 on the new QMainWindow
            self.trang_moi.show()  # Show the new page
            self.pushButton_6.setStyleSheet(
                'font: 75 30pt "Arial";\n'
                "border-color: rgb(255, 216, 228);\n"
                "color: rgb(49, 17, 29);\n"
                "background-color: rgb(255, 216, 228);\n"
                "border-radius: 30px;\n"
                "\n"
                "pressed { background-color: red }"
            )
            self.frame_11.setStyleSheet(
                "border-radius: 30px;\n"
                "border-style: solid;\n"
                "background-color: rgb(255, 216, 228);\n"
                "margin"
            )
        else:
            self.trang_hien_tai = 1
            # Return to the main page
            self.trang_moi.close()  # Close the current page


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()

    # Connect the button click event to the next_page_2 function
    ui.pushButton_search.clicked.connect(ui.next_page_2)
    ui.pushButton_ChamCong.clicked.connect(ui.next_page_3)
    ui.pushButton_EfficacyDayInWeek.clicked.connect(
        ui.show_chart_window_efficacy_day_in_week
    )
    ui.pushButton_AgeEfficacy.clicked.connect(ui.show_chart_window_age_efficacy)
    ui.pushButton_SexEfficacy.clicked.connect(ui.show_chart_window_sex_efficacy)
    ui.pushButton_6.clicked.connect(ui.next_page_6)

    sys.exit(app.exec())
